"""Shared English<->Korean vocabulary for common DB column/table names, so schemas.py
can define tables/columns with plain English identifiers and templates.py can render
natural-language labels in both languages without repeating translations per schema."""

# snake_case English identifier -> (English label, Korean label)
TERMS: dict[str, tuple[str, str]] = {
    # generic
    "id": ("ID", "ID"),
    "name": ("name", "이름"),
    "title": ("title", "제목"),
    "description": ("description", "설명"),
    "status": ("status", "상태"),
    "type": ("type", "종류"),
    "category": ("category", "분류"),
    "created_at": ("creation date", "생성일"),
    "updated_at": ("last updated date", "수정일"),
    "date": ("date", "날짜"),
    "notes": ("notes", "비고"),
    "code": ("code", "코드"),
    "active": ("active status", "활성 여부"),
    "is_active": ("active status", "활성 여부"),
    # people
    "customer": ("customer", "고객"),
    "customer_id": ("customer", "고객"),
    "customer_name": ("customer name", "고객 이름"),
    "employee": ("employee", "직원"),
    "employee_id": ("employee", "직원"),
    "employee_name": ("employee name", "직원 이름"),
    "first_name": ("first name", "이름"),
    "last_name": ("last name", "성"),
    "email": ("email", "이메일"),
    "phone": ("phone number", "전화번호"),
    "address": ("address", "주소"),
    "birth_date": ("birth date", "생년월일"),
    "gender": ("gender", "성별"),
    "age": ("age", "나이"),
    "hire_date": ("hire date", "입사일"),
    "salary": ("salary", "급여"),
    "manager_id": ("manager", "관리자"),
    "user_id": ("user", "사용자"),
    "author_id": ("author", "작가"),
    "author": ("author", "작가"),
    "student_id": ("student", "학생"),
    "student": ("student", "학생"),
    "teacher_id": ("teacher", "교사"),
    "teacher": ("teacher", "교사"),
    "doctor_id": ("doctor", "의사"),
    "doctor": ("doctor", "의사"),
    "patient_id": ("patient", "환자"),
    "patient": ("patient", "환자"),
    "member_id": ("member", "회원"),
    "member": ("member", "회원"),
    "owner_id": ("owner", "주인"),
    "tenant_id": ("tenant", "세입자"),
    "guest_id": ("guest", "투숙객"),
    "guest": ("guest", "투숙객"),
    "user_name": ("username", "사용자명"),
    # commerce
    "product": ("product", "상품"),
    "product_id": ("product", "상품"),
    "product_name": ("product name", "상품명"),
    "price": ("price", "가격"),
    "unit_price": ("unit price", "단가"),
    "quantity": ("quantity", "수량"),
    "stock": ("stock quantity", "재고 수량"),
    "stock_quantity": ("stock quantity", "재고 수량"),
    "order": ("order", "주문"),
    "order_id": ("order", "주문"),
    "order_date": ("order date", "주문일"),
    "total": ("total amount", "총액"),
    "total_amount": ("total amount", "총액"),
    "amount": ("amount", "금액"),
    "discount": ("discount", "할인"),
    "supplier": ("supplier", "공급업체"),
    "supplier_id": ("supplier", "공급업체"),
    "warehouse": ("warehouse", "창고"),
    "warehouse_id": ("warehouse", "창고"),
    "brand": ("brand", "브랜드"),
    "sku": ("SKU", "SKU"),
    "payment_method": ("payment method", "결제 방법"),
    "shipping_address": ("shipping address", "배송지"),
    "cart_id": ("cart", "장바구니"),
    "review": ("review", "리뷰"),
    "rating": ("rating", "평점"),
    # org / finance
    "department": ("department", "부서"),
    "department_id": ("department", "부서"),
    "project": ("project", "프로젝트"),
    "project_id": ("project", "프로젝트"),
    "budget": ("budget", "예산"),
    "account": ("account", "계좌"),
    "account_id": ("account", "계좌"),
    "account_number": ("account number", "계좌번호"),
    "balance": ("balance", "잔액"),
    "transaction": ("transaction", "거래"),
    "transaction_id": ("transaction", "거래"),
    "branch": ("branch", "지점"),
    "branch_id": ("branch", "지점"),
    "loan": ("loan", "대출"),
    "loan_amount": ("loan amount", "대출 금액"),
    "interest_rate": ("interest rate", "이자율"),
    "invoice": ("invoice", "송장"),
    "invoice_id": ("invoice", "송장"),
    "vendor": ("vendor", "거래처"),
    "vendor_id": ("vendor", "거래처"),
    # library / school
    "book": ("book", "도서"),
    "book_id": ("book", "도서"),
    "isbn": ("ISBN", "ISBN"),
    "publisher": ("publisher", "출판사"),
    "borrow_date": ("borrow date", "대출일"),
    "return_date": ("return date", "반납일"),
    "due_date": ("due date", "반납 예정일"),
    "course": ("course", "강좌"),
    "course_id": ("course", "강좌"),
    "class_id": ("class", "학급"),
    "grade": ("grade", "학년"),
    "score": ("score", "점수"),
    "credit": ("credit", "학점"),
    "semester": ("semester", "학기"),
    "enrollment_date": ("enrollment date", "등록일"),
    "major": ("major", "전공"),
    # hospital
    "appointment": ("appointment", "예약"),
    "appointment_id": ("appointment", "예약"),
    "appointment_date": ("appointment date", "예약일"),
    "diagnosis": ("diagnosis", "진단"),
    "prescription": ("prescription", "처방"),
    "room": ("room", "병실"),
    "room_id": ("room", "병실"),
    "specialty": ("specialty", "전문 분야"),
    "insurance": ("insurance", "보험"),
    "medication": ("medication", "약물"),
    "dosage": ("dosage", "용량"),
    # hospitality / booking
    "hotel": ("hotel", "호텔"),
    "hotel_id": ("hotel", "호텔"),
    "reservation": ("reservation", "예약"),
    "reservation_id": ("reservation", "예약"),
    "checkin_date": ("check-in date", "체크인 날짜"),
    "checkout_date": ("check-out date", "체크아웃 날짜"),
    "table_id": ("table", "테이블"),
    "reservation_time": ("reservation time", "예약 시간"),
    "party_size": ("party size", "인원수"),
    "menu_item": ("menu item", "메뉴"),
    "menu_item_id": ("menu item", "메뉴"),
    "ingredient": ("ingredient", "재료"),
    # gym / membership
    "membership": ("membership", "회원권"),
    "membership_id": ("membership", "회원권"),
    "membership_type": ("membership type", "회원권 종류"),
    "start_date": ("start date", "시작일"),
    "end_date": ("end date", "종료일"),
    "trainer_id": ("trainer", "트레이너"),
    "trainer": ("trainer", "트레이너"),
    "session": ("session", "세션"),
    "session_id": ("session", "세션"),
    # blog / cms
    "post": ("post", "게시글"),
    "post_id": ("post", "게시글"),
    "comment": ("comment", "댓글"),
    "comment_id": ("comment", "댓글"),
    "tag": ("tag", "태그"),
    "view_count": ("view count", "조회수"),
    "like_count": ("like count", "좋아요 수"),
    "published_at": ("published date", "게시일"),
    # movie / media
    "movie": ("movie", "영화"),
    "movie_id": ("movie", "영화"),
    "director": ("director", "감독"),
    "genre": ("genre", "장르"),
    "duration": ("duration", "상영 시간"),
    "release_date": ("release date", "개봉일"),
    "actor": ("actor", "배우"),
    "actor_id": ("actor", "배우"),
    "theater": ("theater", "상영관"),
    "theater_id": ("theater", "상영관"),
    "ticket": ("ticket", "티켓"),
    "showtime": ("showtime", "상영 시간"),
    # vehicle / rental
    "vehicle": ("vehicle", "차량"),
    "vehicle_id": ("vehicle", "차량"),
    "model": ("model", "모델"),
    "license_plate": ("license plate", "번호판"),
    "rental": ("rental", "대여"),
    "rental_id": ("rental", "대여"),
    "rental_date": ("rental date", "대여일"),
    "mileage": ("mileage", "주행거리"),
    "driver": ("driver", "운전자"),
    "driver_id": ("driver", "운전자"),
    # additional table/column names (real_estate, airline, insurance, university_research,
    # and assorted columns across the other domains not already covered above)
    "account_type": ("account type", "계좌 종류"),
    "advisor_id": ("advisor", "지도교수"),
    "agent": ("agent", "중개인"),
    "agent_id": ("agent", "중개인"),
    "airport": ("airport", "공항"),
    "booking": ("booking", "예약"),
    "booking_date": ("booking date", "예약일"),
    "capacity": ("capacity", "수용 인원"),
    "citation_count": ("citation count", "인용 수"),
    "city": ("city", "도시"),
    "claim": ("claim", "보험금 청구"),
    "claim_amount": ("claim amount", "청구 금액"),
    "claim_date": ("claim date", "청구일"),
    "client": ("client", "고객"),
    "client_id": ("client", "고객"),
    "commenter_name": ("commenter name", "댓글 작성자"),
    "country": ("country", "국가"),
    "departure_date": ("departure date", "출발일"),
    "destination_id": ("destination", "도착지"),
    "duration_minutes": ("duration in minutes", "소요 시간(분)"),
    "enrollment": ("enrollment", "수강 등록"),
    "flight": ("flight", "항공편"),
    "flight_id": ("flight", "항공편"),
    "floor": ("floor", "층"),
    "grad_student": ("graduate student", "대학원생"),
    "joined_date": ("joined date", "가입일"),
    "license_number": ("license number", "면허 번호"),
    "listed_date": ("listed date", "등록일"),
    "listing": ("listing", "매물"),
    "location": ("location", "위치"),
    "movement_date": ("movement date", "이동일"),
    "movement_type": ("movement type", "이동 유형"),
    "order_item": ("order item", "주문 항목"),
    "order_ticket": ("order ticket", "주문 전표"),
    "orders": ("order", "주문"),
    "origin_id": ("origin", "출발지"),
    "passenger": ("passenger", "승객"),
    "passenger_id": ("passenger", "승객"),
    "policy": ("policy", "보험 증권"),
    "policy_id": ("policy", "보험 증권"),
    "policy_type": ("policy type", "보험 종류"),
    "premium": ("premium", "보험료"),
    "price_per_night": ("price per night", "1박 요금"),
    "professor": ("professor", "교수"),
    "professor_id": ("professor", "교수"),
    "property": ("property", "매물"),
    "property_id": ("property", "매물"),
    "property_type": ("property type", "매물 유형"),
    "publication": ("publication", "논문"),
    "published_year": ("published year", "출판 연도"),
    "reservation_date": ("reservation date", "예약일"),
    "restaurant_table": ("table", "테이블"),
    "room_type": ("room type", "객실 유형"),
    "screen_type": ("screen type", "상영관 유형"),
    "seat_class": ("seat class", "좌석 등급"),
    "session_date": ("session date", "세션 날짜"),
    "show_date": ("show date", "상영일"),
    "showtime_id": ("showtime", "상영 시간"),
    "stock_movement": ("stock movement", "재고 이동"),
    "subject": ("subject", "과목"),
    "theater_room": ("theater room", "상영관"),
    "total_cost": ("total cost", "총 비용"),
    "transaction_date": ("transaction date", "거래일"),
    "transaction_type": ("transaction type", "거래 유형"),
    "unit_cost": ("unit cost", "단가"),
    "warehouse_location": ("warehouse location", "창고 위치"),
    "warehouse_location_id": ("warehouse location", "창고 위치"),
    "year": ("year", "연도"),
    # coffee_shop / veterinary_clinic / conference (new train domains)
    "barista": ("barista", "바리스타"),
    "barista_id": ("barista", "바리스타"),
    "cafe_order": ("order", "주문"),
    "vet": ("vet", "수의사"),
    "vet_id": ("vet", "수의사"),
    "pet_owner": ("pet owner", "반려동물 보호자"),
    "pet": ("pet", "반려동물"),
    "pet_id": ("pet", "반려동물"),
    "species": ("species", "종"),
    "visit": ("visit", "방문"),
    "visit_date": ("visit date", "방문일"),
    "speaker": ("speaker", "발표자"),
    "speaker_id": ("speaker", "발표자"),
    "topic": ("topic", "주제"),
    "attendee": ("attendee", "참가자"),
    "attendee_id": ("attendee", "참가자"),
    "talk": ("talk", "발표"),
    "talk_id": ("talk", "발표"),
    "track": ("track", "트랙"),
    "talk_date": ("talk date", "발표일"),
    "registration": ("registration", "등록"),
    "registered_at": ("registered date", "등록일"),
}


def humanize(identifier: str) -> str:
    """Fallback English label for an identifier not in TERMS: snake_case -> spaced."""
    return identifier.replace("_", " ")


def label_en(identifier: str) -> str:
    if identifier in TERMS:
        return TERMS[identifier][0]
    return humanize(identifier)


def label_ko(identifier: str) -> str:
    if identifier in TERMS:
        return TERMS[identifier][1]
    return humanize(identifier)  # best-effort fallback; every real column should be in TERMS


def pluralize_en(label: str) -> str:
    """Naive English pluralization for a table/collection label used as a bare plural
    noun (e.g. "Show customers", "List all orders") - good enough for this project's
    synthetic single-word/short-phrase table labels, not a general-purpose inflector."""
    if label.endswith(("s", "x", "z", "ch", "sh")):
        return label + "es"
    if label.endswith("y") and label[-2:-1] not in "aeiou":
        return label[:-1] + "ies"
    return label + "s"


def label_en_plural(identifier: str) -> str:
    return pluralize_en(label_en(identifier))
